# Generated by Django 5.2.3 on 2025-06-14 09:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_newsarticle_approved_at_newsarticle_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='NewsArticle'),
            preserve_default=False,
        ),
    ]
